export const techIcons: { [key: string]: string } = {
  'AWS': 'la:aws',
  'AWS EC2': 'simple-icons:amazonec2',
  'Axios': 'simple-icons:axios',
  'Bash': 'devicon-plain:bash',
  'C': 'devicon:c',
  'C++': 'devicon:cplusplus',
  'C++20': 'devicon:cplusplus',
  'Cloudflare': 'devicon:cloudflare',
  'CMake': 'devicon:cmake',
  'CSS3': 'devicon:css3',
  'Cypress': 'devicon-plain:cypressio',
  'D3.js': 'logos:d3',
  'Django': 'vscode-icons:file-type-django',
  'Docker': 'logos:docker-icon',
  'Firebase': 'devicon:firebase',
  'Flask': 'simple-icons:flask',
  'Framer Motion': 'simple-icons:framer',
  'Go': 'logos:go',
  'HTML5': 'devicon:html5',
  'JavaScript': 'devicon:javascript',
  'JavaScript (ES6)': 'devicon:javascript',
  'Jest': 'logos:jest',
  'jQuery': 'devicon-plain:jquery',
  'Linux': 'devicon:linux',
  'MongoDB': 'logos:mongodb-icon',
  'MySQL': 'fontisto:mysql',
  'Next.js': 'devicon:nextjs',
  'Node.js': 'devicon:nodejs',
  'NumPy': 'devicon:numpy',
  'OpenCV': 'devicon:opencv',
  'Postgres': 'logos:postgresql',
  'Postman': 'devicon:postman',
  'Powershell': 'vscode-icons:file-type-powershell',
  'Pytest': 'simple-icons:pytest',
  'Python': 'devicon:python',
  'Python3': 'devicon:python',
  'R': 'devicon:rstudio',
  'Railway': 'simple-icons:railway',
  'React': 'logos:react',
  'Redis': 'devicon:redis',
  'Socket.IO': 'simple-icons:socketdotio',
  'Streamlit': 'devicon:streamlit',
  'TailwindCSS': 'devicon:tailwindcss',
  'TypeScript': 'devicon:typescript',
};
