import { FunctionComponent } from 'react';
import { 
    PythonOriginal,
    JavascriptOriginal,
    TypescriptOriginal,
    COriginal,
    CplusplusOriginal,
    GoOriginalWordmark,
    Html5OriginalWordmark,
    Css3OriginalWordmark,
    ROriginal,
    DjangoPlain,
    FlaskOriginalWordmark,
    ReactOriginal,
    NodejsOriginalWordmark,
    AxiosPlainWordmark,
    SocketioOriginalWordmark,
    TailwindcssOriginalWordmark,
    D3jsOriginal,
    JestPlain,
    CypressioOriginal,
    PytestOriginalWordmark,
    NextjsOriginal,
} from 'devicons-react';


export const techIcons: { [key: string]: FunctionComponent } = {
    "Python3": PythonOriginal,
    "JavaScript (ES6)": JavascriptOriginal,
    "TypeScript": TypescriptOriginal,
    "C": COriginal,
    "C++20": CplusplusOriginal,
    "Go": GoOriginalWordmark,
    "HTML5": Html5OriginalWordmark ,
    "CSS3": Css3OriginalWordmark,
    "R": ROriginal,
    "Django": DjangoPlain,
    "Flask": FlaskOriginalWordmark,
    "React": ReactOriginal,
    "Next.js": NextjsOriginal,
    "Node.js": NodejsOriginalWordmark,
    "Axios": AxiosPlainWordmark,
    "Socket.IO": SocketioOriginalWordmark,
    "TailwindCSS": TailwindcssOriginalWordmark,
    "D3.js": D3jsOriginal,
    "Jest": JestPlain,
    "Cypress": CypressioOriginal,
    "Pytest": PytestOriginalWordmark,
}
