export const techIcons: { [key: string]: string } = {
    "Python": "devicon:python",
    "Python3": "devicon:python",
    "JavaScript (ES6)": "devicon:javascript",
    "TypeScript": "devicon:typescript",
    "C": "devicon:c",
    "C++": "devicon:cplusplus",
    "C++20": "devicon:cplusplus",
    "Go": "logos:go",
    "HTML5": "logos:html-5" ,
    "CSS3": "logos:css-3",
    "R": "devicon:rstudio",
    "Django": "vscode-icons:file-type-django",
    "Flask": "simple-icons:flask",
    "React": "logos:react",
    "Next.js": "devicon:nextjs",
    "Node.js": "devicon:nodejs",
    "Axios": "simple-icons:axios",
    "Socket.IO": "simple-icons:socketdotio",
    "TailwindCSS": "devicon:tailwindcss",
    "D3.js": "logos:d3",
    "Jest": "logos:jest",
    "Cypress": "devicon-plain:cypressio",
    "Pytest": "simple-icons:pytest",
    "Postgres": "logos:postgresql",
    "MySQL": "fontisto:mysql",
    "Docker": "logos:docker-icon",
    "Powershell": "vscode-icons:file-type-powershell",
    "Bash": "devicon-plain:bash"
}
